"""Durable, committed bar archive — the paid-for Databento data, banked once and reused forever.

Why this exists: Databento historical is metered against a finite (free-tier) credit balance, and
the working cache (``data/cache/``) is git-ignored and per-workspace — so every fresh Conductor
workspace / clone re-fetched from scratch and re-burned credits. This archive is the opposite:
**committed to the repo, compressed, fetch-once.** Backtests read it offline and never touch the
network (see ``DatabentoProvider``); the only code that ever spends a credit is ``scripts/data_pull.py``.

Design:
- **Canonical atom = 1-minute.** We store ONLY 1m bars. Every higher timeframe (5m/15m/1h/D1/…) is
  derived locally via ``resample_ohlcv`` at read time. One stored series ⇒ all timeframes, and a
  new timeframe costs zero credits. (Databento's own OHLCV schemas are 1m/1h/1d, and a single 1m
  pull is cheaper than pulling each timeframe separately.)
- **Scope split for holdout discipline.** Reference years (≤ 2024, burned IS/OOS) live under
  ``reference/``; the reserved final holdout (2025+) lives under ``holdout/`` and is **not read
  unless the caller explicitly opts in** (``allow_holdout=True``). Banking the holdout data while
  credits exist is not peeking — but the structural split makes accidental peeking hard.

Layout (all committed):
    data/archive/databento/
      manifest.json                  # human-readable coverage index (regenerated by data_pull)
      reference/<symbol>/M1.parquet  # zstd, tz-aware NY, canonical 1-minute
      holdout/<symbol>/M1.parquet    # sealed: 2025+
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import pandas as pd

from src.core.config import REPO_ROOT
from src.data.normalize import OHLCV_COLS

NY_TZ = "America/New_York"

ARCHIVE_ROOT = REPO_ROOT / "data" / "archive" / "databento"
MANIFEST_PATH = ARCHIVE_ROOT / "manifest.json"

REFERENCE = "reference"
HOLDOUT = "holdout"
#: Years >= this are the reserved final holdout and are sealed behind ``allow_holdout``.
HOLDOUT_START_YEAR = 2025

_PARQUET_COMPRESSION = "zstd"


def _empty() -> pd.DataFrame:
    return pd.DataFrame(columns=OHLCV_COLS, index=pd.DatetimeIndex([], tz=NY_TZ))


def _to_ny(ts) -> pd.Timestamp:
    t = pd.Timestamp(ts)
    return t.tz_localize(NY_TZ) if t.tz is None else t.tz_convert(NY_TZ)


def scope_for_year(year: int) -> str:
    """Which archive scope a calendar year belongs to."""
    return HOLDOUT if year >= HOLDOUT_START_YEAR else REFERENCE


def scope_for_ts(ts) -> str:
    return scope_for_year(_to_ny(ts).year)


def _path(symbol: str, scope: str) -> Path:
    return ARCHIVE_ROOT / scope / symbol / "M1.parquet"


# --- read --------------------------------------------------------------------


def read_1m(symbol: str, scope: str = REFERENCE) -> pd.DataFrame:
    """All archived 1-minute bars for ``symbol`` in one scope (empty if none stored)."""
    path = _path(symbol, scope)
    if not path.exists():
        return _empty()
    df = pd.read_parquet(path)
    if df.index.tz is None:  # defensive: parquet round-trips tz, but localize if it ever drops
        df.index = df.index.tz_localize(NY_TZ)
    return df[OHLCV_COLS].sort_index()


def read_for_range(
    symbol: str, start: datetime, end: datetime, *, allow_holdout: bool = False
) -> pd.DataFrame:
    """Archived 1m bars for ``symbol`` over ``[start, end]``, spanning scopes as needed.

    The reference scope is always consulted. The holdout scope is consulted **only** when
    ``allow_holdout=True`` — so a default backtest can never read the reserved 2025+ data even if
    its date range extends into it.
    """
    lo, hi = _to_ny(start), _to_ny(end)
    frames = [read_1m(symbol, REFERENCE)]
    if allow_holdout:
        frames.append(read_1m(symbol, HOLDOUT))
    df = pd.concat([f for f in frames if len(f)]) if any(len(f) for f in frames) else _empty()
    if len(df):
        df = df[~df.index.duplicated(keep="last")].sort_index()
        df = df.loc[(df.index >= lo) & (df.index <= hi)]
    return df


# --- write -------------------------------------------------------------------


def write_1m(symbol: str, bars: pd.DataFrame, scope: str) -> int:
    """Merge ``bars`` (1-minute OHLCV) into the archive for ``symbol``/``scope``; return total rows.

    Idempotent: merges with anything already stored, de-dupes on timestamp (keeping the latest),
    sorts, and rewrites the zstd Parquet — so re-pulling an overlapping range is harmless.
    """
    path = _path(symbol, scope)
    path.parent.mkdir(parents=True, exist_ok=True)

    incoming = bars[OHLCV_COLS].copy() if len(bars) else _empty()
    existing = read_1m(symbol, scope)
    merged = pd.concat([existing, incoming]) if len(existing) else incoming
    merged = merged[~merged.index.duplicated(keep="last")].sort_index()
    if len(merged):
        merged.to_parquet(path, compression=_PARQUET_COMPRESSION)
    return len(merged)


# --- coverage / manifest -----------------------------------------------------


def _scan() -> dict:
    """Walk the archive and summarise coverage per scope/symbol (start, end, rows)."""
    out: dict[str, dict] = {}
    for scope in (REFERENCE, HOLDOUT):
        scope_dir = ARCHIVE_ROOT / scope
        if not scope_dir.is_dir():
            continue
        for sym_dir in sorted(p for p in scope_dir.iterdir() if p.is_dir()):
            df = read_1m(sym_dir.name, scope)
            if not len(df):
                continue
            out.setdefault(scope, {})[sym_dir.name] = {
                "start": str(df.index[0]),
                "end": str(df.index[-1]),
                "rows": int(len(df)),
            }
    return out


def write_manifest() -> dict:
    """Regenerate ``manifest.json`` from what is actually on disk; return the manifest dict."""
    manifest = {
        "canonical_timeframe": "1m",
        "note": "Higher timeframes are derived at read time via resample_ohlcv. Holdout (2025+) "
        "is sealed: read only with allow_holdout=True.",
        "generated_at": pd.Timestamp.now(tz="UTC").isoformat(),
        "coverage": _scan(),
    }
    ARCHIVE_ROOT.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def symbols(scope: str = REFERENCE) -> list[str]:
    """Archived symbols in a scope."""
    scope_dir = ARCHIVE_ROOT / scope
    if not scope_dir.is_dir():
        return []
    return sorted(p.name for p in scope_dir.iterdir() if p.is_dir() and (p / "M1.parquet").exists())
