"""Durable, committed bar archive — the paid-for Databento data, banked once and reused forever.

Why this exists: Databento historical is metered against a finite (free-tier) credit balance, and
the working cache (``data/cache/``) is git-ignored and per-workspace — so every fresh Conductor
workspace / clone re-fetched from scratch and re-burned credits. This archive is the opposite:
**committed to the repo, compressed, fetch-once.** Backtests read it offline and never touch the
network (see ``DatabentoProvider``); the only code that ever spends a credit is ``scripts/data_pull.py``.

Design:
- **Canonical atom = 1-minute.** We store ONLY 1m bars. Every higher timeframe (5m/15m/1h/D1/…) is
  derived locally via ``resample_ohlcv`` at read time. One stored series ⇒ all timeframes, and a
  new timeframe costs zero credits. (Databento's own OHLCV schemas are 1m/1h/1d, and a single 1m
  pull is cheaper than pulling each timeframe separately.)
- **Scope split for holdout discipline.** Reference years (≤ 2024, burned IS/OOS) live under
  ``reference/``; the reserved final holdout (2025+) lives under ``holdout/`` and is **not read
  unless the caller explicitly opts in** (``allow_holdout=True``). Banking the holdout data while
  credits exist is not peeking — but the structural split makes accidental peeking hard.

Layout (all committed). Bars are **chunked one file per calendar year** so no single file grows
large (each ~3–5 MB) and git diffs stay small; a year file is immutable once written:
    data/archive/databento/
      manifest.json                     # human-readable coverage index (regenerated by data_pull)
      reference/<symbol>/<year>.parquet # zstd, tz-aware NY, canonical 1-minute (e.g. 2017.parquet)
      holdout/<symbol>/<year>.parquet   # sealed: 2025+
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

import pandas as pd

from src.core.config import REPO_ROOT
from src.data.normalize import OHLCV_COLS

NY_TZ = "America/New_York"

ARCHIVE_ROOT = REPO_ROOT / "data" / "archive" / "databento"
MANIFEST_PATH = ARCHIVE_ROOT / "manifest.json"

REFERENCE = "reference"
HOLDOUT = "holdout"
#: Years >= this are the reserved final holdout and are sealed behind ``allow_holdout``.
HOLDOUT_START_YEAR = 2025

_PARQUET_COMPRESSION = "zstd"

#: A per-year chunk file, e.g. ``2017.parquet``. (Distinguishes chunks from any legacy consolidated
#: ``M1.parquet``, so a read ignores the latter and the one-time migration can target it.)
_YEAR_FILE = re.compile(r"^(\d{4})\.parquet$")


def _empty() -> pd.DataFrame:
    return pd.DataFrame(columns=OHLCV_COLS, index=pd.DatetimeIndex([], tz=NY_TZ))


def _to_ny(ts) -> pd.Timestamp:
    t = pd.Timestamp(ts)
    return t.tz_localize(NY_TZ) if t.tz is None else t.tz_convert(NY_TZ)


def scope_for_year(year: int) -> str:
    """Which archive scope a calendar year belongs to."""
    return HOLDOUT if year >= HOLDOUT_START_YEAR else REFERENCE


def scope_for_ts(ts) -> str:
    return scope_for_year(_to_ny(ts).year)


def _symbol_dir(symbol: str, scope: str) -> Path:
    return ARCHIVE_ROOT / scope / symbol


def _year_file(symbol: str, scope: str, year: int) -> Path:
    return _symbol_dir(symbol, scope) / f"{year}.parquet"


# --- read --------------------------------------------------------------------


def read_1m(symbol: str, scope: str = REFERENCE) -> pd.DataFrame:
    """All archived 1-minute bars for ``symbol`` in one scope — every per-year chunk concatenated
    (empty if none stored)."""
    d = _symbol_dir(symbol, scope)
    if not d.is_dir():
        return _empty()
    files = sorted(p for p in d.iterdir() if _YEAR_FILE.match(p.name))
    if not files:
        return _empty()
    df = pd.concat([pd.read_parquet(p) for p in files])
    if df.index.tz is None:  # defensive: parquet round-trips tz, but localize if it ever drops
        df.index = df.index.tz_localize(NY_TZ)
    df = df[OHLCV_COLS]
    return df[~df.index.duplicated(keep="last")].sort_index()


def read_for_range(
    symbol: str, start: datetime, end: datetime, *, allow_holdout: bool = False
) -> pd.DataFrame:
    """Archived 1m bars for ``symbol`` over ``[start, end]``, spanning scopes as needed.

    The reference scope is always consulted. The holdout scope is consulted **only** when
    ``allow_holdout=True`` — so a default backtest can never read the reserved 2025+ data even if
    its date range extends into it.
    """
    lo, hi = _to_ny(start), _to_ny(end)
    frames = [read_1m(symbol, REFERENCE)]
    if allow_holdout:
        frames.append(read_1m(symbol, HOLDOUT))
    df = pd.concat([f for f in frames if len(f)]) if any(len(f) for f in frames) else _empty()
    if len(df):
        df = df[~df.index.duplicated(keep="last")].sort_index()
        df = df.loc[(df.index >= lo) & (df.index <= hi)]
    return df


# --- write -------------------------------------------------------------------


def write_1m(symbol: str, bars: pd.DataFrame, scope: str) -> int:
    """Merge ``bars`` (1-minute OHLCV) into the archive for ``symbol``/``scope``, **chunked one file
    per calendar year**; return total rows now stored in the scope.

    Incoming bars are split by their NY calendar year and each year is merged into its own chunk
    file (so a year-boundary pull lands bars in the right files). Idempotent per year: de-dupes on
    timestamp (keeping the latest), sorts, rewrites only the touched year files — re-pulling an
    overlapping range is harmless.
    """
    if len(bars):
        d = _symbol_dir(symbol, scope)
        d.mkdir(parents=True, exist_ok=True)
        incoming = bars[OHLCV_COLS]
        for year, chunk in incoming.groupby(incoming.index.year):
            path = _year_file(symbol, scope, int(year))
            merged = pd.concat([pd.read_parquet(path), chunk]) if path.exists() else chunk
            merged = merged[OHLCV_COLS]
            merged = merged[~merged.index.duplicated(keep="last")].sort_index()
            merged.to_parquet(path, compression=_PARQUET_COMPRESSION)
    return len(read_1m(symbol, scope))


# --- coverage / manifest -----------------------------------------------------


def _scan() -> dict:
    """Walk the archive and summarise coverage per scope/symbol (start, end, rows)."""
    out: dict[str, dict] = {}
    for scope in (REFERENCE, HOLDOUT):
        scope_dir = ARCHIVE_ROOT / scope
        if not scope_dir.is_dir():
            continue
        for sym_dir in sorted(p for p in scope_dir.iterdir() if p.is_dir()):
            df = read_1m(sym_dir.name, scope)
            if not len(df):
                continue
            out.setdefault(scope, {})[sym_dir.name] = {
                "start": str(df.index[0]),
                "end": str(df.index[-1]),
                "rows": int(len(df)),
            }
    return out


def write_manifest() -> dict:
    """Regenerate ``manifest.json`` from what is actually on disk; return the manifest dict."""
    manifest = {
        "canonical_timeframe": "1m",
        "note": "Higher timeframes are derived at read time via resample_ohlcv. Holdout (2025+) "
        "is sealed: read only with allow_holdout=True.",
        "generated_at": pd.Timestamp.now(tz="UTC").isoformat(),
        "coverage": _scan(),
    }
    ARCHIVE_ROOT.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def symbols(scope: str = REFERENCE) -> list[str]:
    """Archived symbols in a scope (those with at least one per-year chunk file)."""
    scope_dir = ARCHIVE_ROOT / scope
    if not scope_dir.is_dir():
        return []
    return sorted(
        p.name for p in scope_dir.iterdir()
        if p.is_dir() and any(_YEAR_FILE.match(f.name) for f in p.iterdir())
    )
